version:"3.7"
services: 
  mysql:# 2do servici
    image: mysql:5.7
    env_file: .env
    container_name: mysql 
    restart: unless-stopped 
    tty:true
    ports: 
      -33069:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - DB_HOST=
      - DB_DATABASE=
      - DB_USERNAME=
      - DB_PASSWORD=

  php:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: php 
    volumes:
      - ./src:/var/www/html 
    ports:
      -80:80


